name:                A Web site

author:
 name:               John Doe
 url:                http://john.doe.example/

url:                 
full-url:            http://john.doe.example
ganalytics:          UA-XXXXXX-Y    # Optional
