name:                A Web site
copyright-start:     YYYY

author:
 name:               John Doe
 url:                http://john.doe.example/

url:                 
full-url:            http://john.doe.example
ganalytics:          #UA-XXXXXX-Y    # Optional; uncomment to enable

portal:    # Optional integration with <http://code.s.zeid.me/portal>
 url:                #//portal.john.doe.example/    # Uncomment to enable
 highlight:          john.doe.example
 theme:              new
