#!/usr/bin/env bash

# This file is executed after the site is generated, but before it is
# deployed (moved from _gen/ to _site/).  If you need anything to be
# done at this time, put it here.  You can also use a different
# language by changing the shebang line above.
