layouts_dir:         ./_template/layouts
plugins_dir:         ./_template/plugins

permalink:           /blog/:year/:month/:day/:title/
highlighter:         pygments
category-dir:        /blog/categories
tag-dir:             /blog/tags

exclude:             [COPYING,COPYING.md,LICENSE,LICENSE.md,Makefile,README,README.md]

stylus:
 path:               ./_template/_styles

portal:
 max-icons: 16
