#!/bin/bash

if [ -n "$1" ]; then
 dir=$(readlink -m "$1")
else
 echo "Usage: $0 directory [template-repository]" >&2
 exit 2
fi

if [ -n "$2" ]; then
 repo=$2
else
 repo=https://bitbucket.org/scottywz/site-design.git
fi

if [ ! -e "$dir" ]; then
 mkdir -p "$dir"
fi

if [ ! -d "$dir" ]; then
 echo "error: $dir exists but is not a directory" >&2
 exit 1
fi

tpl_dir="$dir"/_template

git clone "$repo" "$tpl_dir"

if [ ! -e "$dir"/Makefile ]; then
 cp -a "$tpl_dir"/root/Makefile "$dir"/Makefile
fi

if [ ! -e "$dir"/_config.yml ]; then
 cp -a "$tpl_dir"/root/_config.yml "$dir"/_config.yml
fi

if [ ! -e "$dir"/_config.styl ]; then
 cp -a "$tpl_dir"/root/_config.styl "$dir"/_config.styl
fi

if [ ! -e "$dir"/_postbuild ]; then
 cp -a "$tpl_dir"/root/_postbuild "$dir"/_postbuild
 chmod +x "$dir"/_postbuild
fi

if [ ! -e "$dir"/_redirects ]; then
 cp -a "$tpl_dir"/root/_redirects "$dir"/_redirects
fi

if [ ! -e "$dir"/index.md ]; then
 cp -a "$tpl_dir"/root/index.md "$dir"/index.md
fi

mkdir -p "$dir"/_comments
mkdir -p "$dir"/_drafts
mkdir -p "$dir"/_posts
mkdir -p "$dir"/_postfiles
mkdir -p "$dir"/_static
