name:                A Web site
copyright-start:     YYYY

author:
 name:               John Doe
 meta:               # if set, replaces author.name in <meta name="author" />
 url:                http://john.doe.example/

url:                 
full-url:            http://john.doe.example
default-scheme:      http    # only necessary with protocol-relative (full-)url
ganalytics:          #UA-XXXXXX-Y    # Optional; uncomment to enable

freecomment:    # Free/libre comment system <http://code.s.zeid.me/freecomment>
 enabled:            #True    # Uncomment to enable
 highlight:     # Comments with these Gravatar ID(s) will be highlighted
  - 16d113840f999444259f73bac9ab8b10    # someone@example.com

internet-defense-league:    # Internet Defense League campaigns
 # Note:  any variable set here will be passed to the `window._idl` object.
 enabled:            #True    # Uncomment to enable
 test:               #True    # Uncomment to test a campaign
 # Optional settings; blank values mean to use the defaults:
 campaign:           # The campaign to show (default: show all campaigns)
 variant:            # The variant to use (e.g. banner, modal; default: banner)
 url:                # URL of custom message

portal:         # Optional integration with <http://code.s.zeid.me/portal>
 url:                #//portal.john.doe.example/    # Uncomment to enable
 highlight:          john.doe.example
 theme:              new
 max-icons:          16    # Controls the width of the portal's iframe (n*24px)
